
			<script type="text/javascript">
			require(["react","react-dom","PartslogicUi"],function(React, ReactDOM, PartslogicUi) {
				/******************************
				** PartsLogic Component: Search Bar
				** Sept 16, 2022 RJ support@partslogic.com
				*******************************/

				window.React = React
				window.ReactDOM = ReactDOM
				window.PartslogicUi = PartslogicUi

				window.PartslogicUi.config({
				   API_KEY: '22e5026d-7cb8-4f9d-9439-a409d0e3b816',
				  });
				const fitmentContainer = document.querySelector("#pl-fitment-selector-container");

				window.ReactDOM.render(
				  window.React.createElement(PartslogicUi.WsmFitmentSelectorWrapper, {
					styled: true,
					groupId: 75196,
					orientation: "horizontal", 
					onSubmit: function (data) {
					  window.location.href = `/search-pl?fitment=${encodeURIComponent(data)}`
					},
				  }),
				  fitmentContainer
				);	

			});
			</script>

<!-- Optional CSS to make adjustments on the specific page. The example below is hiding some UI elements on the page -->
<style>

	.header-info{
	    display:none;
	}
	.page-wrapper{
	    padding-top:0px !important;
	    
	}


</style>
