<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var $block \Magento\Review\Block\Customer\Recent */
?>

<?php if ($block->getReviews() && count($block->getReviews())): ?>
<div class="block block-reviews-dashboard">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('My Recent Reviews') ?></strong>
        <a class="action view" href="<?php /* @escapeNotVerified */ echo $block->getAllReviewsUrl() ?>"><span><?php /* @escapeNotVerified */ echo __('View All') ?></span></a>
    </div>
    <div class="block-content">
        <ol class="items">
        <?php foreach ($block->getReviews() as $_review): ?>
            <li class="item">
                <strong class="product-name"><a href="<?php /* @escapeNotVerified */ echo $block->getReviewUrl($_review->getReviewId()) ?>"><?php echo $block->escapeHtml($_review->getName()) ?></a></strong>
                <?php if ($_review->getSum()): ?>
                <?php $rating = $_review->getSum() / $_review->getCount() ?>
                    <div class="rating-summary">
                         <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $rating; ?>%">
                             <div class="rating-result__stars">
                                 <?php
                                 $half_star_id = round( (int)$rating / 20 );
                                 for($i = 0; $i < 5; $i++){
                                     if( $i < $half_star_id ) {
                                         echo '<span class="rating-star__full"></span>';
                                     }
                                     if( $i == $half_star_id ) {
                                         echo '<span class="rating-star__half"></span>';
                                     }
                                     if( $i > $half_star_id ) {
                                         echo '<span class="rating-star__empty"></span>';
                                     }
                                 } ?>
                             </div>
                         </div>
                     </div>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
